name: 🚀 Suggest a New AI Tool
description: Suggest a free AI tool to be added to the list
title: "[TOOL]: "
labels: ["new-tool", "suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new AI tool! Please fill out the information below.

  - type: input
    id: tool-name
    attributes:
      label: Tool Name
      description: What's the name of the AI tool?
      placeholder: e.g., ChatGPT, Midjourney, etc.
    validations:
      required: true

  - type: input
    id: tool-url
    attributes:
      label: Tool URL
      description: What's the official website URL?
      placeholder: https://example.com
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category does this tool belong to?
      options:
        - Design Inspiration
        - Design Tools
        - Mockups & Presentation
        - Web Animation & Motion
        - 3D Logo & Branding
        - Stock Images
        - Stock Videos
        - Fonts
        - Icons & Illustrations
        - 3D Models & Textures
        - 3D AI Tools
        - UI/UX Design & Prototyping
        - Presentations & Documents
        - Audio, Speech & Voice
        - Image & AI Generation
        - Video & Motion Tools
        - Productivity & Research
        - Business & Legal Tools
        - AI Chatbots & Assistants
        - Code Assistants
        - AI APIs & Platforms
        - Open Source Models
        - AI for Education
        - AI for Marketing
        - AI for Data Science
        - AI for Gaming
        - AI for Healthcare
        - AI for Finance
        - AI Browser Extensions
        - AI Mobile Apps
        - No-Code AI Platforms
        - AI for Accessibility
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of what the tool does (1-2 sentences)
      placeholder: AI-powered tool that generates...
    validations:
      required: true

  - type: dropdown
    id: free-tier
    attributes:
      label: Free Tier Available?
      description: Does this tool have a meaningful free tier?
      options:
        - "Yes - Completely Free"
        - "Yes - Free with Limitations"
        - "Yes - Free Trial Only"
        - "No - Paid Only"
    validations:
      required: true

  - type: textarea
    id: free-tier-details
    attributes:
      label: Free Tier Details
      description: What's included in the free tier? (limits, features, etc.)
      placeholder: |
        - 100 credits per month
        - Access to basic models
        - Watermarked exports
        - etc.

  - type: dropdown
    id: ai-powered
    attributes:
      label: AI-Powered?
      description: Does this tool use AI/ML technology?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have verified the tool is currently active and working
          required: true
        - label: I have checked it's not already listed in the repository
          required: true
        - label: The tool has a meaningful free tier (not just a 3-day trial)
          required: true
        - label: I have tested the tool myself
          required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant information about this tool?
      placeholder: |
        - Why is this tool useful?
        - What makes it stand out?
        - Any tips for using it?
